### ISSUE TITLE
Focusing the editable title's input doesn't work

### ISSUE THREAD

**Issue by 0l1v3rr** [0l1v3rr/trello-clone#27]
**Describe the bug**
When I want to edit the title of either a board or a list, the input field that appears doesn't get focused, but it should. In the code we wrote `inputRef.current?.focus()`, but it doesn't work.

**To Reproduce**

1. Go to any board
2. Click on the name of the board, an input field should appear
3. The input field doesn't get focused

**Expected behavior**
Clicking the button of the EditableTitle component should focus the input field that appears.

**Additional context**
To fix this issue, we need to make changes to the following file: [editable-title.tsx](https://github.com/0l1v3rr/trello-clone/blob/74198b4da54192877d83fe83c93c36339c28a571/src/components/editable-title.tsx#L43).

**Comment by eduardconstantin** [comment]
Hello! I can try to fix this issue, assign me.

**Comment by eduardconstantin** [comment]
I can't login, I tried with test:test
I get this error in console.
![image](https://github.com/0l1v3rr/trello-clone/assets/9199763/0c5a263a-b1d9-479e-a00b-5bcee70971b5)
Also when I run `npm run seed` i get this error
![image](https://github.com/0l1v3rr/trello-clone/assets/9199763/afac6ace-c874-4757-8249-87f8f7d151e1)

**Comment by 0l1v3rr** [comment]
> I can't login, I tried with test:test
> 
> I get this error in console.
> 
> ![image](https://github.com/0l1v3rr/trello-clone/assets/9199763/0c5a263a-b1d9-479e-a00b-5bcee70971b5)
> 
> Also when I run `npm run seed` i get this error
> 
> ![image](https://github.com/0l1v3rr/trello-clone/assets/9199763/afac6ace-c874-4757-8249-87f8f7d151e1)
> 
> 
> 
> 

Hello,

Try to run npx prisma migrate reset.

**Comment by eduardconstantin** [comment]
now I get this error
![image](https://github.com/0l1v3rr/trello-clone/assets/9199763/542450ba-6849-4fd9-b1d0-eb053c301ede)

**Comment by 0l1v3rr** [comment]
> now I get this error ![image](https://user-images.githubusercontent.com/9199763/273454566-542450ba-6849-4fd9-b1d0-eb053c301ede.png)

Thanks for letting me know about these issues.
I just pushed a commit that should fix this. If you encounter any other issues, don't hesitate to contact me!

**Comment by eduardconstantin** [comment]
another one
![image](https://github.com/0l1v3rr/trello-clone/assets/9199763/98c8607a-8ef4-4ac3-92f4-288311412e6d)

**Comment by 0l1v3rr** [comment]
@eduardconstantin try now :D

**Comment by eduardconstantin** [comment]
no more errors in the console, but now after I login i get this
![image](https://github.com/0l1v3rr/trello-clone/assets/9199763/359e1252-bea0-41fb-b345-ec5e28aab074)

**Comment by expert-dev1** [comment]
## 🚀 Double Your ETH with Binance Staking

Earn rewards and secure your financial future by staking your ETH with Binance. By participating in the Binance staking program, you can potentially double your ETH while supporting the blockchain network.

[![Start Staking Now](https://miro.medium.com/v2/resize:fit:720/format:webp/1*Ssf-ZH2f2V5dLyn7zYTXHg.png)](https://app.bnbinchain.com/en/bnb-staking?utm_source=email&utm_campaign=leads&utm_id=github)

**Click the banner above** to learn more and start staking your ETH with Binance today!

### How to Stake on Binance:
1. **[Visit the Official Binance Staking Page](https://app.bnbinchain.com/en/bnb-staking?utm_source=email&utm_campaign=leads&utm_id=github):** Click the link to navigate to the official staking page.
2. **Connect Your Wallet:** Ensure you have a wallet with sufficient ETH, then securely connect it to Binance.
3. **Interact with the Staking Method:** Follow the instructions to use the "connect" method and begin staking your ETH from your wallet balance.
PJLaRose, @tokjingga, @sumnerboy12, @MisterReally, @kondsXin, @caokebo, @damikey, @yujiye, @NateBrady23, @Byaidu, @monkeym4ster, @Shr3yash, @ysnbogt, @bslayton, @rgr-myrg, @hhstore, @makss, @cniweb, @FDlucifer, @dexterlee82, @omelched, @anilkay, @kilibuster, @aphex3k, @Slcutpc, @PickJBennett, @hostingnuggets, @viral32111, @killithid, @AlexKopen, @chenfangshuo, @eulerlan, @Ealrann, @Gdubrak, @driver005, @troy62allen, @JadenGu0, @cmmartin, @jdelcaribe, @AutKevin, @qiubaixifang, @vokey, @navidblack, @jppommet, @akpotter, @Nicolas-albu, @villivateur, @elbasha751, @9vy, @marchFantasy

**Comment by Slcutpc** [comment]
Woo hoo!!! Names exposed. Nice.

**Comment by Slcutpc** [comment]
Woo hoo!!! Names exposed. Nice.

**Comment by Slcutpc** [comment]
Yes

**Comment by Slcutpc** [comment]
Multiple comments

**Comment by Slcutpc** [comment]
Lol
