### ISSUE TITLE
Create favicon, icon, and apple-icon for the app

### ISSUE THREAD

**Issue by 0l1v3rr** [0l1v3rr/trello-clone#29]
**Describe the solution you'd like**
We would like to have icons to make the application look nicer in production.

**Additional context**
- You can find a ready-made SVG logo [here](https://github.com/0l1v3rr/trello-clone/blob/master/src/assets/logo.svg).  
- Important info about using icons in the Next.js app router: [https://nextjs.org/docs/app/api-reference/file-conventions/metadata/app-icons](https://nextjs.org/docs/app/api-reference/file-conventions/metadata/app-icons)

**Comment by burhanharoon** [comment]
Hey @0l1v3rr, could you assign this issue to me? I have extensive experience with next.js and would be happy to contribute. Thank you!

**Comment by 0l1v3rr** [comment]
Hello @burhanharoon , of course! :)
