### ISSUE TITLE
Clicking a card after closing an other card is not working

### ISSUE THREAD

**Issue by 0l1v3rr** [0l1v3rr/trello-clone#30]
**Describe the bug**
When I'm on the board page and want to click on a card, the page of the card appears (it's a popup). When I close this window with the `X` on the top left, it closes. However, when I want to click on a card again (in a list), the popup does not appear, only after a hard refresh.

**To Reproduce**
1. Navigate to a page of a board
2. Click on a card, a popup window should appear with a different URL
3. Close this popup with the X on the top left
4. Click on a card again. Now, the popup won't appear.

**Expected behavior**
I expect this to work without having to refresh the page every time I close a card.

**Additional context**
If you have further questions, I'm more than happy to answer them.

**Comment by RKOsvk** [comment]
can you assignee me to this issue?

**Comment by sanjaykumaryada** [comment]
Hi @RKOsvk  i would like to contribute, can you assign this to me?

**Comment by 0l1v3rr** [comment]
Hello guys,

Looks like @RKOsvk won't be responding, so @sanjaykumaryada if you still would like to contribute, I can assign you this issue.

**Comment by sanjaykumaryada** [comment]
Yes please @0l1v3rr  assign this to me.
