### ISSUE TITLE
The overflew card popup should be scrollable

### ISSUE THREAD

**Issue by 0l1v3rr** [0l1v3rr/trello-clone#31]
**Describe the bug**
When I navigate to a page of a card (this is a popup) and this card has tons of content that overflows the screen, I cannot scroll the page to see the overflowing content.

**To Reproduce**

1. Open a board page
2. Click on a card - a popup should appear
3. Fill the description with tons of data, or create a bunch of labels
4. You cannot scroll

**Expected behavior**
If a card has a lot of content that doesn't fit on one screen, the page should be scrollable.

**Additional context**
We use shadcn/ui as UI components.

**Comment by masterHAWK99** [comment]
I started working on this, please assign me.
