### ISSUE TITLE
The editor resizes outside of the container

### ISSUE THREAD

**Issue by masterHAWK99** [0l1v3rr/trello-clone#36]
**Describe the bug**
When text is too long and doesn't have spaces, the editor resizes outside of the container.

**To Reproduce**

1. Open a board page
2. Click on a card - a popup should appear
3. Fill the description with tons of data (without spaces)
4. The editor resizes outside of the container

**Expected behavior**
Text line should always break when doesn't fit.

**Screenshots**
![image](https://github.com/0l1v3rr/trello-clone/assets/60447475/0e98da36-9a37-48bd-ab56-43a9afd145a0)

**Comment by eduardconstantin** [comment]
I'll take this one
