### ISSUE TITLE
The favicon has a white background

### ISSUE THREAD

**Issue by 0l1v3rr** [0l1v3rr/trello-clone#38]
**Describe the bug**
#29  - @burhanharoon I just noticed on dark mode, that the favicon has a white background, which doesn't look too good. I think the background should be transparent. Would you fix this, please?

**Screenshots**
<img width="238" alt="image" src="https://github.com/0l1v3rr/trello-clone/assets/77695356/5c2b0840-2a0f-43d5-8aed-8ae31eb8ad15">

**Comment by burhanharoon** [comment]
Sure, will do. @0l1v3rr

**Comment by 0l1v3rr** [comment]
Thanks! :)
