### ISSUE TITLE
Glich shows when selecting image while creating board

### ISSUE THREAD

**Issue by masterHAWK99** [0l1v3rr/trello-clone#41]
**Describe the bug**
While creating a new board, when "Background" changed to "Image", image didn't show correctly. First, there's no image, then some image show for a second and finally good image appears.

**To Reproduce**

1. Go to Create board
2. Click on Image in Background section

**Expected behavior**
The correct image should appear the first time.

**Screenshots**
https://github.com/0l1v3rr/trello-clone/assets/60447475/d77e6374-bc5e-4eb1-b4b3-35df4f31116a

**Comment by 0l1v3rr** [comment]
Hello @masterHAWK99 ,

Thanks for opening this issue. Would you like to work on this?

**Comment by masterHAWK99** [comment]
Sure, assign me please :)
