### ISSUE TITLE
The page must be reloaded in order to view the newly created board

### ISSUE THREAD

**Issue by masterHAWK99** [0l1v3rr/trello-clone#42]
**Describe the bug**
When a new board is created, it redirects to its page. However, when we go back to the main page, the new board does not appear until we reload the page.

**To Reproduce**

1. Go to Create board
2. Create board
3. Go to main page (where is list of boards)

**Expected behavior**
Created board should be on the list

**Screenshots**
https://github.com/0l1v3rr/trello-clone/assets/60447475/38605d58-aa3a-4edc-96c9-1a2ea799bf0e

**Comment by sanjaykumaryada** [comment]
Hi @0l1v3rr @masterHAWK99  i would like to contribute, can you assign this to me?

**Comment by 0l1v3rr** [comment]
Hello @sanjaykumaryada, be my guest! :)
